// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7KEoXIXadwoPi9wmv5tgxddDKex4K6JA',
    appId: '1:8425252069:web:002eb1700e5bc10cf9a00c',
    messagingSenderId: '8425252069',
    projectId: 'kemo-6f3e9',
    authDomain: 'kemo-6f3e9.firebaseapp.com',
    storageBucket: 'kemo-6f3e9.appspot.com',
    measurementId: 'G-PSCLNJ7CHV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8IEHRX8sR47_80fExAfIy9dO-ZuRXIwA',
    appId: '1:8425252069:android:eaeaea1b587b592ef9a00c',
    messagingSenderId: '8425252069',
    projectId: 'kemo-6f3e9',
    storageBucket: 'kemo-6f3e9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtQfJYtQFIRacemco7z18AM_LZGu-l6z0',
    appId: '1:8425252069:ios:b344407b854ebd95f9a00c',
    messagingSenderId: '8425252069',
    projectId: 'kemo-6f3e9',
    storageBucket: 'kemo-6f3e9.appspot.com',
    iosClientId: '8425252069-en151hi81m26423p7rii30b8krpvd7fo.apps.googleusercontent.com',
    iosBundleId: 'com.kemo.app',
  );
}
