name: Merge DEV
on: 
  pull_request:
    branches: ['dev']
  push:
    # branches: ['dev'] //TODO: remove after testing

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      #init
      - uses: actions/checkout@v2
      - uses: dart-lang/setup-dart@v1
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '2.10.1'
          channel: 'stable'
      - name: Install dependencies
        run: flutter pub get
      

      #actual work
      - name: Verify formatting dart
        run: |
          libFiles=`find ./lib/ -type f -not -regex ".*\.\(freezed\|gr\|g\).dart" -not -name "*.arb"`
          for file in $libFiles
          do
              dart format --line-length 100 --output=none --set-exit-if-changed $file
          done

      - uses: dblock/create-a-github-issue@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          filename: .github/templates/ISSUE_TEMPLATE.md

      - uses: invertase/github-action-dart-analyzer@v1
        with:
          fatal-infos: true
          fatal-warnings: true
          annotate: true
          annotate-only: false
          working-directory: ./
        

#  test:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v2
#      - uses: dart-lang/setup-dart@v1
#      - uses: subosito/flutter-action@v2
#        with:
#          flutter-version: '2.5.3'
#          channel: 'stable'
#
#      - name: Install dependencies
#        run: flutter pub get
#
#      - name: Copy .env.example into .env file
#        run: |
#          cp ./assets/.env.example ./assets/.env
#
#      - name: Run tests flutter
#        run: flutter test