name: Merge to DEV

########## WF-STEPS ##########
# => format documents
# => lint code
# => flutter analyze
# => build apk + add as artefact
# => test apk on firebase testlab
# => send slack with apk

on:
  pull_request:
    branches: ["dev"]
  push:
    branches: ["dev"]

env:
  WF_URI: "uri"

jobs:
  ###################### format ######################
  files-format-check:
    runs-on: ubuntu-latest
    steps:
      #init
      - uses: actions/checkout@v2
      - uses: dart-lang/setup-dart@v1
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "2.10.1"
          channel: "stable"
      - name: setVariable
        run: |
          echo "WF_URI=$GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID" >> $GITHUB_ENV
      - name: Install dependencies
        run: flutter pub get
      # actual steps
      - name: Verify formatting dart
        id: files-format-check-action
        run: |
          libFiles=`find ./lib/ -type f -not -regex ".*\.\(freezed\|gr\|g\).dart" -not -name "*.arb"`
          for file in $libFiles
          do
            result=$(dart format --line-length 10 --output=none --set-exit-if-changed $file)
          done
      - name: Create issue if failed
        if: failure()
        uses: dblock/create-a-github-issue@v3
        id: new-issue
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_WORKFLOW: GITHUB_WORKFLOW
          JOB_TITLE: "files-format-check"
          BODY_TEXT: ""
          URI_WF: ${{ env.WF_URI }}
      - name: Send Slack Message - New Issue
        if: always() && steps.new-issue.outputs.number != ''
        id: slack
        uses: slackapi/slack-github-action@v1.18.0
        with:
          payload: |
            {
            "text": "GitHub Action build result: ",
            "blocks": [
              {
                "type": "header",
                "text": {
                  "type": "plain_text",
                  "text": "New issue occcure while Merge to DEV - files-format-check",
                  "emoji": true
                }
              },
              {
                "type": "section",
                "fields": [
                  {
                    "type": "mrkdwn",
                    "text": "*Created issue:*"
                  },
                  {
                    "type": "mrkdwn",
                    "text": "<${{ steps.new-issue.outputs.url }}|Open Issue>"
                  }
                ]
              },
              {
                "type": "section",
                "fields": [
                  {
                    "type": "mrkdwn",
                    "text": "*Related to pull request:*"
                  },
                  {
                    "type": "mrkdwn",
                    "text": "<${{ github.event.pull_request.html_url }}|Open PR>"
                  }
                ]
              },
              {
                "type": "section",
                "fields": [
                  {
                    "type": "mrkdwn",
                    "text": "*From workflow:*"
                  },
                  {
                    "type": "mrkdwn",
                    "text": "<${{ env.WF_URI }}|Open WF>"
                  }
                ]
              }
            ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_ISSUES }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK

  ###################### lint ######################
  code-lint:
    runs-on: ubuntu-latest
    steps:
      # init
      - uses: actions/checkout@v2
      - uses: dart-lang/setup-dart@v1
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "2.10.1"
          channel: "stable"
      - name: Install dependencies
        run: flutter pub get
      - name: setVariable
        run: |
          echo "WF_URI=$GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID" >> $GITHUB_ENV
        # actual steps
      - name: Analyze code
        uses: invertase/github-action-dart-analyzer@v1
        id: lint-action
        with:
          fatal-infos: true
          fatal-warnings: true
          annotate: true
          annotate-only: false
          working-directory: ./
      - name: Create issue if failed
        if: failure()
        uses: dblock/create-a-github-issue@v3
        id: new-issue
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_WORKFLOW: GITHUB_WORKFLOW
          JOB_TITLE: "code-lint"
          BODY_TEXT: "Analyzer outputs:\nInfos: ${{steps.lint-action.outputs.infos}}\nWarnings: ${{steps.lint-action.outputs.warnings}}\nErrors: ${{steps.lint-action.outputs.errors}}"
          URI_WF: ${{ env.WF_URI }}
      - name: Send Slack Message - New Issue
        if: always() && steps.new-issue.outputs.number != ''
        id: slack
        uses: slackapi/slack-github-action@v1.18.0
        with:
          payload: |
            {
            "text": "GitHub Action build result: ",
            "blocks": [
              {
                "type": "header",
                "text": {
                  "type": "plain_text",
                  "text": "New issue occcure while Merge to DEV - Analyzer-LINT",
                  "emoji": true
                }
              },
              {
                "type": "section",
                "fields": [
                  {
                    "type": "mrkdwn",
                    "text": "*Created issue:*"
                  },
                  {
                    "type": "mrkdwn",
                    "text": "<${{ steps.new-issue.outputs.url }}|Open Issue>"
                  }
                ]
              },
              {
                "type": "section",
                "fields": [
                  {
                    "type": "mrkdwn",
                    "text": "*Related to pull request:*"
                  },
                  {
                    "type": "mrkdwn",
                    "text": "<${{ github.event.pull_request.html_url }}|Open PR>"
                  }
                ]
              },
              {
                "type": "section",
                "fields": [
                  {
                    "type": "mrkdwn",
                    "text": "*From workflow:*"
                  },
                  {
                    "type": "mrkdwn",
                    "text": "<${{ env.WF_URI }}|Open WF>"
                  }
                ]
              }
            ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_ISSUES }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK

  ###################### flutter analyze ######################
  flutter-analyze:
    runs-on: ubuntu-latest
    steps:
      # init
      - uses: actions/checkout@v2
      - uses: dart-lang/setup-dart@v1
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "2.10.1"
          channel: "stable"
      - name: Install dependencies
        run: result=$(flutter pub get)
      - name: setVariable
        run: |
          echo "WF_URI=$GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID" >> $GITHUB_ENV
        # actual steps
      - name: Flutter analyze
        id: analyze-action
        run: |
          flutter analyze
      - name: Create issue if failed
        if: failure()
        uses: dblock/create-a-github-issue@v3
        id: new-issue
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_WORKFLOW: GITHUB_WORKFLOW
          JOB_TITLE: "flutter-analyze"
          BODY_TEXT: ""
          URI_WF: ${{ env.WF_URI }}
      - name: Send Slack Message - New Issue
        if: always() && steps.new-issue.outputs.number != ''
        id: slack
        uses: slackapi/slack-github-action@v1.18.0
        with:
          payload: |
            {
            "text": "GitHub Action build result: ",
            "blocks": [
              {
                "type": "header",
                "text": {
                  "type": "plain_text",
                  "text": "New issue occcure while Merge to DEV - flutter-analyzer",
                  "emoji": true
                }
              },
              {
                "type": "section",
                "fields": [
                  {
                    "type": "mrkdwn",
                    "text": "*Created issue:*"
                  },
                  {
                    "type": "mrkdwn",
                    "text": "<${{ steps.new-issue.outputs.url }}|Open Issue>"
                  }
                ]
              },
              {
                "type": "section",
                "fields": [
                  {
                    "type": "mrkdwn",
                    "text": "*Related to pull request:*"
                  },
                  {
                    "type": "mrkdwn",
                    "text": "<${{ github.event.pull_request.html_url }}|Open PR>"
                  }
                ]
              },
              {
                "type": "section",
                "fields": [
                  {
                    "type": "mrkdwn",
                    "text": "*From workflow:*"
                  },
                  {
                    "type": "mrkdwn",
                    "text": "<${{ env.WF_URI }}|Open WF>"
                  }
                ]
              }
            ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_ISSUES }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK

  ###################### build APK ######################
  build-APK:
    runs-on: ubuntu-latest
    needs: ["files-format-check", "code-lint", "flutter-analyze"]
    permissions:
      contents: "read"
      id-token: "write"
    steps:
      # init
      - uses: actions/checkout@v2
      - uses: dart-lang/setup-dart@v1
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "2.10.1"
          channel: "stable"
      - uses: actions/setup-java@v1
        with:
          java-version: "12.x"
      - name: Install dependencies
        run: flutter pub get
      - name: setVariable
        run: |
          echo "WF_URI=$GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID" >> $GITHUB_ENV
        # actual steps
      - name: build APK
        id: build-apk
        run: |
          flutter build apk
      - name: Create issue if failed
        if: failure()
        uses: dblock/create-a-github-issue@v3
        id: new-issue
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_WORKFLOW: GITHUB_WORKFLOW
          JOB_TITLE: "Build APK"
          BODY_TEXT: "Build apk failed with error:\n${{toJSON(steps.build-apk.outputs)}}"
          URI_WF: ${{ env.WF_URI }}
      - name: Send Slack Message - New Issue
        if: always() && steps.new-issue.outputs.number != ''
        id: slack
        uses: slackapi/slack-github-action@v1.18.0
        with:
          payload: |
            {
            "text": "GitHub Action build result: ",
            "blocks": [
              {
                "type": "header",
                "text": {
                  "type": "plain_text",
                  "text": "New issue occcure while Merge to DEV - build-APK",
                  "emoji": true
                }
              },
              {
                "type": "section",
                "fields": [
                  {
                    "type": "mrkdwn",
                    "text": "*Created issue:*"
                  },
                  {
                    "type": "mrkdwn",
                    "text": "<${{ steps.new-issue.outputs.url }}|Open Issue>"
                  }
                ]
              },
              {
                "type": "section",
                "fields": [
                  {
                    "type": "mrkdwn",
                    "text": "*Related to pull request:*"
                  },
                  {
                    "type": "mrkdwn",
                    "text": "<${{ github.event.pull_request.html_url }}|Open PR>"
                  }
                ]
              },
              {
                "type": "section",
                "fields": [
                  {
                    "type": "mrkdwn",
                    "text": "*From workflow:*"
                  },
                  {
                    "type": "mrkdwn",
                    "text": "<${{ env.WF_URI }}|Open WF>"
                  }
                ]
              }
            ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_ISSUES }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
      - name: Save artefact
        uses: actions/upload-artifact@v1
        with:
          name: release-apk
          path: build/app/outputs/apk/release/app-release.apk

  ###################### Firebase TestLab ######################
  test-lab:
    needs: [build-APK]
    runs-on: ubuntu-latest
    steps:
      # init
      - uses: actions/checkout@v2
      - name: "Authenticate to Google Cloud"
        id: "auth"
        uses: "google-github-actions/auth@v0"
        with:
          credentials_json: "${{ secrets.GC_AUTH }}"
      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v0"
      - name: setVariable
        run: |
          echo "WF_URI=$GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID" >> $GITHUB_ENV
      # actual steps
      - name: Download app APK
        uses: actions/download-artifact@v1
        with:
          name: release-apk
      - name: Run tests on Firebase Test Lab
        id: run-test-lab
        run: |
          gcloud firebase test android run --app=release-apk/app-release.apk > test-results.txt
      - name: Create issue if failed
        if: failure()
        uses: dblock/create-a-github-issue@v3
        id: new-issue
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_WORKFLOW: GITHUB_WORKFLOW
          JOB_TITLE: "Send to Test-Lab FIREBASE"
          URI_WF: ${{ env.WF_URI }}
      - name: Send Slack Message
        if: always() && steps.new-issue.outputs.number != ''
        id: slack
        uses: slackapi/slack-github-action@v1.18.0
        with:
          payload: |
            {
            "text": "GitHub Action build result: ",
            "blocks": [
              {
                "type": "header",
                "text": {
                  "type": "plain_text",
                  "text": "New issue occcure while Merge to DEV - firebase-test-lab",
                  "emoji": true
                }
              },
              {
                "type": "section",
                "fields": [
                  {
                    "type": "mrkdwn",
                    "text": "*Created issue:*"
                  },
                  {
                    "type": "mrkdwn",
                    "text": "<${{ steps.new-issue.outputs.url }}|Open Issue>"
                  }
                ]
              },
              {
                "type": "section",
                "fields": [
                  {
                    "type": "mrkdwn",
                    "text": "*Related to pull request:*"
                  },
                  {
                    "type": "mrkdwn",
                    "text": "<${{ github.event.pull_request.html_url }}|Open PR>"
                  }
                ]
              },
              {
                "type": "section",
                "fields": [
                  {
                    "type": "mrkdwn",
                    "text": "*From workflow:*"
                  },
                  {
                    "type": "mrkdwn",
                    "text": "<${{ env.WF_URI }}|Open WF>"
                  }
                ]
              }
            ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_ISSUES }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
      - name: Save artefact
        uses: actions/upload-artifact@v1
        with:
          name: TestLab-results
          path: test-results.txt

  ###################### Inform about success PULL ######################
  success-slack-pull:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    needs: ["test-lab"]
    env:
      TESTLAB_RESULTS: ""
    steps:
      # init
      - uses: actions/checkout@v2
      - name: setVariable
        run: |
          echo "WF_URI=$GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID" >> $GITHUB_ENV
      # actual steps
      - name: Send Slack Message Seccess DEV
        id: slack
        uses: slackapi/slack-github-action@v1.18.0
        with:
          payload: |
            {
            "text": "GitHub Action build result: ",
            "blocks": [
              {
                "type": "header",
                "text": {
                  "type": "plain_text",
                  "text": "GHA Pull request check to DEV - SUCCESS",
                  "emoji": true
                }
              },
              {
                "type": "section",
                "fields": [
                  {
                    "type": "mrkdwn",
                    "text": "*From workflow:*"
                  },
                  {
                    "type": "mrkdwn",
                    "text": "<${{ env.WF_URI }}|Open WF>"
                  }
                ]
              }
            ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_PR }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK

  ###################### Inform about success PUSH ######################
  success-slack:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    needs: ["test-lab"]
    env:
      TESTLAB_RESULTS: ""
    steps:
      # init
      - uses: actions/checkout@v2
      - name: setVariable
        run: |
          echo "WF_URI=$GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID" >> $GITHUB_ENV
      # actual steps
      - name: Send Slack Message Seccess DEV
        id: slack
        uses: slackapi/slack-github-action@v1.18.0
        with:
          payload: |
            {
            "text": "GitHub Action build result: ",
            "blocks": [
              {
                "type": "header",
                "text": {
                  "type": "plain_text",
                  "text": "GHA Push check to DEV - SUCCESS",
                  "emoji": true
                }
              },
              {
                "type": "section",
                "fields": [
                  {
                    "type": "mrkdwn",
                    "text": "*From workflow:*"
                  },
                  {
                    "type": "mrkdwn",
                    "text": "<${{ env.WF_URI }}|Open WF>"
                  }
                ]
              }
            ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_PUSH }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
