name: test-MIRDA

on: [push]

env:
  TEST: $GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID

jobs:
  pokus:
    runs-on: ubuntu-latest
    steps:
      - name: echo
        run: |
          echo ${{ env.POKUS }}

      - uses: actions/checkout@v2
      - name: Create issue
        uses: dblock/create-a-github-issue@v3
        id: create-issue-format
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_WORKFLOW: GITHUB_WORKFLOW
          JOB_TITLE: ""
          BODY_TEXT: "abraka dabra"
          SERVER_URL: ${{ env.TEST }}
