name: test-MIRDA

on: [push]

env:
  TEST: "baf"

jobs:
  pokus:
    runs-on: ubuntu-latest
    steps:
      - name: echo
        run: |
          echo $GITHUB_SERVER_URL
          echo: $GITHUB_REPOSITORY
          echo $GITHUB_RUN_ID
      - name: Create issue
        uses: dblock/create-a-github-issue@v3
        id: create-issue-format
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_WORKFLOW: GITHUB_WORKFLOW
          JOB_TITLE: "files-format-check"
          BODY_TEXT: ""
          SERVER_URL: ${{GITHUB_SERVER_URL}}
          REPOSITORY: ${{GITHUB_REPOSITORY}}
          RUN_ID: ${{GITHUB_RUN_ID}}
